@startuml

package game.brick_break{
    package entities{
        class Sprite {
            # x: int
            # y: int
            # width: int
            # height: int
        }
        class CollideSprite extends Sprite {
            - minX: int
            - maxX: int
            - minY: int
            - maxY: int
        }
        class Ball extends game.brick_break.entities.Sprite{
            - stop: boolean
            - dxStop: int
            - dx: int
            - dy: int
            + resetState(): void
            + getCenter(): int
            + getMiddle(): int
        }
        package paddle{
            enum PaddleType{
                NORMAL
                LONG
                SHORT
                LASER
            }
            class Paddle extends game.brick_break.entities.CollideSprite {
                - dx: int
                + move(): void
            }
        }
        package border{
            enum BorderType{
                TOP
                BOTTOM
                LEFT
                RIGHT
            }
            class Border extends game.brick_break.entities.CollideSprite {
                - borderType: BorderType
            }
        }
        package brick{
            enum BrickType{
                BLUE
                GREEN
                RED
                YELLOW
            }
            class Brick extends game.brick_break.entities.CollideSprite {
                - life: int
                - score: int
                - destroy: boolean
                + minusLife(): void

            }
            class UnbreakableBrick extends Brick {

            }
        }
    }
}

Paddle -- PaddleType

@enduml